
import { Router } from 'express';
import healthCheck from './health-check.js';
import stripeRouter from './stripe.js';
import ecommerceRouter from './ecommerce/index.js';
import checkoutRouter from './checkout.js';
import stripeWebhookRouter from './stripe-webhook.js';
import emailRouter from './email.js';
import ordersRouter from './orders.js';
import contactRouter from './contact.js';
import newsletterRouter from './newsletter.js';
import blogRouter from './blog.js';
import oauthRouter from './oauth.js';
import twoFARouter from './2fa.js';
import agentsRouter from './agents.js';
import sessionsRouter from './sessions.js';
import securityRouter from './security.js';
import analyticsRouter from './analytics.js';
import webhooksRouter from './webhooks.js';
import apiKeysRouter from './api-keys.js';
import rateLimitsRouter from './rate-limits.js';
import quotasRouter from './quotas.js';
import teamsRouter from './teams.js';
import searchRouter from './search.js';
import workflowsRouter from './workflows.js';
import recommendationsRouter from './recommendations.js';
import reportsRouter from './reports.js';
import insightsRouter from './insights.js';
import adminAnalyticsRouter from './admin/analytics.js';
import adminWebhooksRouter from './admin/webhooks.js';
import adminRateLimitsRouter from './admin/rate-limits.js';
import adminQuotasRouter from './admin/quotas.js';
import adminTeamsRouter from './admin/teams.js';
import adminPerformanceRouter from './admin/performance.js';
import adminCacheRouter from './admin/cache.js';

const router = Router();

export default () => {
    router.get('/health', healthCheck);
    router.use('/stripe', stripeRouter);
    router.use('/ecommerce', ecommerceRouter);
    router.use('/checkout', checkoutRouter);
    router.use('/webhook/stripe', stripeWebhookRouter);
    router.use('/send-email', emailRouter);
    router.use('/orders', ordersRouter);
    router.use('/contact', contactRouter);
    router.use('/newsletter', newsletterRouter);
    router.use('/blog', blogRouter);
    router.use('/oauth', oauthRouter);
    router.use('/2fa', twoFARouter);
    router.use('/agents', agentsRouter);
    router.use('/sessions', sessionsRouter);
    router.use('/security', securityRouter);
    router.use('/analytics', analyticsRouter);
    router.use('/webhooks', webhooksRouter);
    router.use('/api-keys', apiKeysRouter);
    router.use('/rate-limits', rateLimitsRouter);
    router.use('/quotas', quotasRouter);
    router.use('/teams', teamsRouter);
    router.use('/search', searchRouter);
    router.use('/workflows', workflowsRouter);
    router.use('/recommendations', recommendationsRouter);
    router.use('/reports', reportsRouter);
    router.use('/insights', insightsRouter);
    router.use('/admin/analytics', adminAnalyticsRouter);
    router.use('/admin/webhooks', adminWebhooksRouter);
    router.use('/admin/rate-limits', adminRateLimitsRouter);
    router.use('/admin/quotas', adminQuotasRouter);
    router.use('/admin/teams', adminTeamsRouter);
    router.use('/admin/performance', adminPerformanceRouter);
    router.use('/admin/cache', adminCacheRouter);

    return router;
};
