
import { MODELS } from '@/data/modelDatabase.js';

export const calculateTokenCount = (text) => {
  if (!text) return 0;
  // Simple heuristic: 1 token ~= 4 chars in English
  return Math.ceil(text.length / 4);
};

export const formatResponseTime = (ms) => {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
};

export const parseCommandInput = (input) => {
  return input.trim();
};

export async function* generateStreamingEffect(text, chunkSize = 5, delayMs = 10) {
  let currentIndex = 0;
  while (currentIndex < text.length) {
    const chunk = text.slice(currentIndex, currentIndex + chunkSize);
    currentIndex += chunkSize;
    yield chunk;
    if (delayMs > 0) {
      await new Promise(resolve => setTimeout(resolve, delayMs));
    }
  }
}

export const simulateModelResponse = async (prompt, modelName, temperature = 0.7) => {
  // Mock sophisticated responses based on prompt keywords
  const pLower = prompt.toLowerCase();
  let response = '';

  if (pLower.includes('compare') || pLower.includes('vs')) {
    response = `## Model Comparison Analysis\n\nBased on your request to compare models, here is a breakdown utilizing the capabilities of **${modelName}** at temperature ${temperature}.\n\n### 1. Context Handling\nModel A exhibits stronger recall at 32k tokens, whereas Model B degrades after 16k.\n\n### 2. Output Formatting\nBoth models adhere well to JSON output requests, but Model A requires fewer few-shot examples.\n\n**Verdict:** Depending on hardware limits, the optimal choice leans toward the higher parameter model if VRAM allows.`;
  } else if (pLower.includes('code') || pLower.includes('react') || pLower.includes('python')) {
    response = `Certainly! Here is the code snippet you requested, generated by **${modelName}**.\n\n\`\`\`python\nimport asyncio\nimport aiohttp\nfrom bs4 import BeautifulSoup\n\nasync def fetch_page(url):\n    async with aiohttp.ClientSession() as session:\n        async with session.get(url) as response:\n            html = await response.text()\n            soup = BeautifulSoup(html, 'html.parser')\n            return soup.title.string if soup.title else "No Title"\n\nasync def main():\n    urls = ["https://example.com", "https://example.org"]\n    tasks = [fetch_page(url) for url in urls]\n    results = await asyncio.gather(*tasks)\n    print(results)\n\nif __name__ == "__main__":\n    asyncio.run(main())\n\`\`\`\n\nThis script demonstrates basic asynchronous web scraping.`;
  } else if (pLower.includes('docker') || pLower.includes('ubuntu') || pLower.includes('hardware')) {
    response = `### Hardware & Deployment Configuration\n\nTo configure this stack using **${modelName}**, follow these steps:\n\n1. **Install Dependencies**:\n   \`\`\`bash\n   sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit\n   \`\`\`\n2. **Docker Compose Setup**:\n   Create a \`docker-compose.yml\` with the following structure allocating your GPUs using the \`deploy\` and \`resources\` directives.\n3. **Verify VRAM**:\n   Ensure you have sufficient VRAM allocated before spinning up the container.`;
  } else {
    response = `I am a simulated response from **${modelName}** (Temp: ${temperature}).\n\nYour prompt: "${prompt}"\n\nTo see more specific capabilities, try asking me to write code, compare technical concepts, or draft a research summary.`;
  }

  return response;
};

export const saveConversationToLocalStorage = (id, conversation) => {
  try {
    const history = JSON.parse(localStorage.getItem('simulator_history') || '{}');
    history[id] = {
      timestamp: new Date().toISOString(),
      messages: conversation
    };
    localStorage.setItem('simulator_history', JSON.stringify(history));
  } catch (e) {
    console.error("Failed to save conversation", e);
  }
};

export const loadConversationFromLocalStorage = (id) => {
  try {
    const history = JSON.parse(localStorage.getItem('simulator_history') || '{}');
    return history[id]?.messages || [];
  } catch (e) {
    console.error("Failed to load conversation", e);
    return [];
  }
};

export const exportConversation = (conversation, format = 'txt') => {
  let content = '';
  let mimeType = 'text/plain';
  let filename = `odysseus_sim_${new Date().getTime()}`;

  if (format === 'json') {
    content = JSON.stringify(conversation, null, 2);
    mimeType = 'application/json';
    filename += '.json';
  } else {
    content = conversation.map(m => `[${m.timestamp}] ${m.role.toUpperCase()}:\n${m.content}\n`).join('\n----------------------------------------\n\n');
    filename += '.txt';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};

// Utility functions for formatting
export const formatJSON = (json) => {
  try {
    return JSON.stringify(typeof json === 'string' ? JSON.parse(json) : json, null, 2);
  } catch (e) {
    return String(json);
  }
};

export const createTableFromData = (data) => {
  if (!Array.isArray(data) || data.length === 0) return '';
  const headers = Object.keys(data[0]);
  let table = `| ${headers.join(' | ')} |\n| ${headers.map(() => '---').join(' | ')} |\n`;
  data.forEach(row => {
    table += `| ${headers.map(h => row[h] || '').join(' | ')} |\n`;
  });
  return table;
};

export const syntaxHighlight = (code, language) => {
  // In a real app, this might wrap code in HTML spans. 
  // Here we rely on react-syntax-highlighter in the component.
  return code;
};
